### ISSUE TITLE
Mutable variable in anonumous functions

### ISSUE THREAD

**Issue by dido18** [MCSN-project2014/APproject#31]
In FSharp we connot use a mutable variable in a anonymous function
The program in FunW@p 
```
fun outside_adder() fun(int) int {
       var sum int = 10
       return fun(x int) int {
            sum += x
           return sum
       }
}
```

is translated in fsharp:

``` f#
let outadd = 
    let mutable sum = 10
    
    fun  x  -> 
        sum <- sum + x        
        sum

```
But mutable variable sum is used in an invalid way, because variables cannot be captured by closures. 
there are two possibilities:
* remove the use of the mutable
*using a heap allocated mutable reference cell via "ref" and "!" .

**Comment by teto1992** [comment]
fixed using ref everywhere and closures
