### ISSUE TITLE
Fibonacci Testing

### ISSUE THREAD

**Issue by teto1992** [MCSN-project2014/APproject#32]
I wrote the funW@P code for the Fibonacci sequence as:

fun fib(n int) int{
	var retVal int = -1;
	if  n == 0 {
		retVal = 0;
	}
	if  n == 1 {
		retVal = 1;
	}
	else {
		retVal = (fib(n-1) + fib(n-2));
	}
	return retVal;
}

fun main(){
	return fib(5);
}

Unfortunately the parsing doesn't produce any result and throws an Exception which is not handled. Any idea? Is my syntax OK?

**Comment by Mene90** [comment]
the problem is the 'return' inside a main function. Because, from the point of view of semantic rules, this kind of statement is not implemented for main function.

**Comment by Mene90** [comment]
Anyway now the parser manages this kind of problems
